hpc<-read.table("./household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
subhbc<-hpc[hpc$Date %in% c("1/2/2007","2/2/2007") ,]
gap <- as.numeric(subhbc$Global_active_power)
datetime<-strptime(paste(subhbc$Date, subhbc$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
png("plot3.png", width=480, height=480)
submet1 <- as.numeric(subhbc$Sub_metering_1)
submet2 <- as.numeric(subhbc$Sub_metering_2)
submet3 <- as.numeric(subhbc$Sub_metering_3)
plot(datetime, subMetering1, type="l", col="green", ylab="Energy Submetering", xlab="")
lines(datetime, subMetering2, type="l", col="red")
lines(datetime, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("green", "red", "blue"))
dev.off()